### ISSUE TITLE
Header: Make blog logo link customizable

### ISSUE THREAD

**Issue by lixk28** [lixk28/Alice#3]
Maybe it's better to provide a customizable argument in `config.toml`:

```toml
[params.header]
    # "baseurl" or "imgurl" or "https://somewhere.com"
    logoTarget = "baseurl"
```

So that users won't have to create their own `header.html` just for specifying the jump location when clicking the logo.
