### ISSUE TITLE
PostCard: Make thumbnail link customizable

### ISSUE THREAD

**Issue by lixk28** [lixk28/Alice#7]
Related: https://github.com/Gasiyu/Alice/commit/cc3ec496976931ba6ec4547632a8f3df606d21fd

Maybe it's better to provide a customizable argument in `config.toml`:

```toml
[params.postcard]
    # "posturl" or "imgurl"
    thumbTarget = "imgurl"
```

So that users won't have to override the default `post-card.html` just for specifying the jump location when clicking the thumbnail.
