### ISSUE TITLE
PostCard: Show post description

### ISSUE THREAD

**Issue by lixk28** [lixk28/Alice#8]
Related: https://github.com/Gasiyu/Alice/commit/c3ee6ac4d0bbdf64204931e13f665d5cca758a90

Maybe it's better to provide a customizable argument in `config.toml`:

```toml
[params.postcard]
    showDescription = false
```

So that users won't have to override the default `post-card.html` just for showing desciptions.
